# Generated by Django 4.0.8 on 2022-12-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyMaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='responsestatus',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='responsestatus',
            old_name='user_id',
            new_name='user',
        ),
    ]
